### ISSUE TITLE
Muy bien resuelto el ejercicio, se nota que lo has trabajado

### ISSUE THREAD

**Issue by vicenlu** [Spanioulis/Sprint-1#3]
https://github.com/Spanioulis/Sprint-1/blob/c1e10d5fc6282cbc8d737351de21e5008fb0dc4d/nivel-3/index.html#L2

**Comment by Spanioulis** [comment]
Muchas gracias Luis!

He tomado nota ya de los otros puntos, aunque en el sprint-2 ya estoy intentando obviar información redundante.

Un saludo
